import { Metadata } from 'next'
import { MainLayout } from '@daffa/core/layouts'

export default MainLayout

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Daffa Portfolio',
    description: 'Generated by daffakbar13',
  }
}
